on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

concurrency:
  group: cicd
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Python version
        env:
          FUGUE_SQL_BUILD_CPP: 0
        run: |
          pip install -e .

      - name: Install CPP version
        env:
          FUGUE_SQL_BUILD_CPP: 1
        run: |
          pip install -e .

      - name: Test
        run: |
          make test

#-------------------------------------------------------------------------------
  build_cpp_wheels:
    name: Build CPP wheels on ${{ matrix.os }} ${{ matrix.cpv }}
    runs-on: ${{ matrix.os }}
    #if: github.event_name == 'release' && github.event.action == 'published' && !github.event.release.prerelease

    strategy:
      matrix:
        os:
          - ubuntu-18.04
          #- windows-latest
          #- macos-latest
        cpv:
          #- "cp36*"
          - "cp37*"
          - "cp38*"
          #- "cp39*"
          #- "cp310*"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.1.3

      - name: Build wheels
        env:
          CIBW_BUILD:  ${{ matrix.cpv }}
          # Don't build osx 10.6 (no C++11 support)
          CIBW_SKIP: "*macosx_10_6*"
          CIBW_ENVIRONMENT: FUGUE_SQL_BUILD_CPP=1
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          name: cpp
          path: ./wheelhouse/*.whl

#-------------------------------------------------------------------------------
  build_cpp_sdist:
    name: Build CPP source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: Build sdist
        env:
          FUGUE_SQL_BUILD_CPP: 1
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: cpp
          path: dist/*.tar.gz

  build_py_sdist:
    name: Build Python source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: Build sdist
        env:
          FUGUE_SQL_BUILD_CPP: 0
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: py
          path: dist/*.tar.gz

#-------------------------------------------------------------------------------
  deploy_cpp:
    needs:
      - test
      - build_cpp_wheels
      - build_cpp_sdist

    runs-on: ubuntu-latest

    # Only publish when a GitHub Release is created.
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cpp
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  deploy_py:
    needs:
      - test
      - build_py_sdist

    runs-on: ubuntu-latest

    # Only publish when a GitHub Release is created.
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: py
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
